# Generated by Django 2.1 on 2021-05-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='covid',
            fields=[
                ('row_num', models.AutoField(db_column='row_num', primary_key=True, serialize=False)),
                ('ResponseID', models.CharField(blank=True, db_column='ResponseID', max_length=25, null=True, unique=True, verbose_name='Qualtrics ID')),
                ('startdate', models.DateField(blank=True, db_column='startdate', verbose_name='Survey start date')),
                ('enddate', models.DateField(blank=True, db_column='enddate', verbose_name='Survey end date')),
                ('first_name', models.CharField(blank=True, db_column='first_name', max_length=30, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, db_column='last_name', max_length=30, null=True, verbose_name='Last name')),
                ('birthday', models.DateField(db_column='birthday', verbose_name='Birthday')),
                ('address', models.TextField(blank=True, db_column='address', null=True, verbose_name='Address for gift card')),
                ('primary_phone', models.CharField(blank=True, db_column='primary_phone', max_length=30, null=True, verbose_name='Primary Phone Number')),
                ('secondary_phone', models.CharField(blank=True, db_column='secondary_phone', max_length=30, null=True, verbose_name='Secondary Phone Number')),
                ('email', models.TextField(blank=True, db_column='email', null=True, verbose_name='Email Address')),
                ('type', models.CharField(blank=True, db_column='type', max_length=30, null=True, verbose_name='Type of the COVID19 Survey')),
                ('first_childname', models.CharField(blank=True, db_column='first_childname', max_length=30, null=True, verbose_name='Child one first name')),
                ('second_childname', models.CharField(blank=True, db_column='second_childname', max_length=30, null=True, verbose_name='Child two first name')),
                ('child_lastname', models.CharField(blank=True, db_column='child_lastname', max_length=30, null=True, verbose_name='Child last name')),
                ('child_dob', models.DateField(blank=True, db_column='child_dob', null=True, verbose_name='Child Birthday')),
                ('cohort_id', models.CharField(blank=True, db_column='cohort_id', max_length=10, null=True, verbose_name='Cohort ID')),
            ],
            options={
                'verbose_name_plural': 'COVID19 Survey',
                'db_table': 'charm_covid',
                'managed': True,
            },
        ),
    ]
