# Generated by Django 3.2.3 on 2021-05-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='enddate',
            field=models.DateField(blank=True, db_column='enddate', null=True, verbose_name='Survey end date'),
        ),
        migrations.AlterField(
            model_name='covid',
            name='startdate',
            field=models.DateField(blank=True, db_column='startdate', null=True, verbose_name='Survey start date'),
        ),
    ]
