# Generated by Django 2.1 on 2021-05-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='archallcontact',
            fields=[
                ('row_num', models.AutoField(db_column='row_num', primary_key=True, serialize=False)),
                ('ARCHID', models.CharField(db_column='ARCHID', max_length=10, verbose_name='ARCH ID')),
                ('currdate', models.DateField(db_column='currdate', verbose_name='Date of contact information')),
                ('address', models.TextField(blank=True, db_column='address', null=True, verbose_name='Address')),
                ('move_home', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], db_column='move_home', max_length=10, null=True, verbose_name='Plan to move home')),
                ('move_home_address', models.TextField(blank=True, db_column='move_home_address', null=True, verbose_name='New address plan to move')),
                ('move_home_date', models.DateField(blank=True, db_column='move_home_date', null=True, verbose_name='Date of moving to new home')),
                ('phone_num', models.CharField(blank=True, db_column='phone_num', max_length=200, null=True, verbose_name='Primary Phone Number')),
                ('text_permission', models.CharField(blank=True, db_column='text_permission', max_length=5, null=True, verbose_name='Permission to text this number')),
                ('text_num', models.CharField(blank=True, db_column='text_num', max_length=200, null=True, verbose_name='Phone Number for texting')),
                ('other_phone', models.CharField(blank=True, db_column='other_phone', max_length=200, null=True, verbose_name='Additional Phone Number')),
                ('other_text_permission', models.CharField(blank=True, db_column='other_text_permission', max_length=5, null=True, verbose_name='Permission to text this number')),
                ('email', models.CharField(blank=True, db_column='email', max_length=150, null=True, verbose_name='Email Address')),
                ('ad_email', models.CharField(blank=True, db_column='ad_email', max_length=150, null=True, verbose_name='Additional email Address')),
                ('prefer_contact', models.CharField(blank=True, choices=[('Text', 'Text'), ('Email', 'Email'), ('call', 'call'), ('Any of the above!', 'Any of the above!')], db_column='prefer_contact', max_length=20, null=True, verbose_name='Preferred contact method')),
                ('social_media', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], db_column='social_media', max_length=10, null=True, verbose_name='Follow social media')),
                ('facebook', models.CharField(blank=True, db_column='facebook', max_length=150, null=True, verbose_name='Facebook')),
                ('Instagram', models.CharField(blank=True, db_column='Instagram', max_length=150, null=True, verbose_name='Instagram')),
                ('Twitter', models.CharField(blank=True, db_column='Twitter', max_length=150, null=True, verbose_name='Twitter')),
                ('contact_a', models.TextField(blank=True, db_column='contact_a', null=True, verbose_name='Alternate contact name')),
                ('contact_aphone', models.CharField(blank=True, db_column='contact_aphone', max_length=200, null=True, verbose_name='Phone number of alternate contact')),
                ('contact_aemail', models.CharField(blank=True, db_column='contact_aemail', max_length=80, null=True, verbose_name='Email of alternate contact')),
                ('contact_aaddress', models.CharField(blank=True, db_column='contact_aaddress', max_length=200, null=True, verbose_name='Mailing address of alternate contact')),
                ('contact_b', models.TextField(blank=True, db_column='contact_b', null=True, verbose_name='Other alternate contact name')),
                ('contact_bphone', models.CharField(blank=True, db_column='contact_bphone', max_length=200, null=True, verbose_name='Phone number of other alternate contact')),
                ('source', models.CharField(blank=True, db_column='source', max_length=30, null=True, verbose_name='Source of the contact information')),
                ('initial', models.CharField(blank=True, db_column='initial', max_length=10, null=True, verbose_name='Please enter your initial')),
                ('qualtrics_id', models.CharField(blank=True, db_column='qualtrics_id', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'ARCH All Contact Information',
                'db_table': 'arch_all_contact',
                'managed': True,
            },
        ),
    ]
