# Generated by Django 3.2.3 on 2021-05-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_archallcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archtrack',
            name='echoreconsent',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('YES', 'YES'), ('NO', 'NO')], db_column='ECHOreconsent', max_length=10, null=True, verbose_name='ECHO Reconsent'),
        ),
    ]
